### ISSUE TITLE
Error WiFiManager

### ISSUE THREAD

**Issue by nvalw** [runo4938/esp32-s3_st7789#1]
In platform.ini

lib_deps = 
	gyverlibs/EncButton@^3.4
	esphome/ESPAsyncWebServer-esphome@^3.1.0
	gyverlibs/GyverNTP@^1.3.1
	bodmer/TFT_eSPI@^2.5.43
	esphome/ESP32-audioI2S@^2.0.7
	C:\Users\admin\Documents\Arduino\libraries\WiFiManager\
	bblanchon/ArduinoJson@^6.21.4
	gyverlibs/Unixtime

What s it? 	C:\Users\admin\Documents\Arduino\libraries\WiFiManager\

Это вызывает ошибки компиляции. Попытка подбросить библу похожую посылает подальше...
Второй вопрос, я не спец в VSC, как потом сделать запись в SPIFFS?

А так проект неплохой, тем более уже на относительно более новой платформе чем другие.

**Comment by runo4938** [comment]
Запись в SPIFFS первоначально надо загрузить из меню Platformio "Upload
Filesystem image". Загружается все из папки DATA. После загрузки должны
заиграть станции. Потом можно будет зайти на Веб Страницу по IP адресу в
нижней части дисплея. В меню "File Manager" можно загрузить playlist.txt,
вписать свои стации, не больше 30 станций. Хотя можно в программе
отредактировать и на большее, потом перекомпилировать.
WiFiManager Версия у меня
* @author Creator tzapu
 * @author tablatronix
 * @version 0.0.0
 * @license MIT
#include в том виде и platformio.ini должны откомпилироваться и загрузиться
без серьезных ошибок. Там предупреждения появляются и все, но не мешают.

чт, 22 февр. 2024 г. в 19:13, nvalw ***@***.***>:

**Comment by runo4938** [comment]
Я выложил свою папку WiFiManager

**Comment by nvalw** [comment]
Папочку Lib c фонтами добавьте...  Я взял ее с прошлых версий...
Проект ваш хорош и многие на 4пда спрашивали у меня как он мне, проверял ли я его, т.к. я дал ссыль еще тогда на первую версию.
И если вы будете свое детище регулярно обновлять, то уж поверьте рекламу я вам там сделаю... в ветке про интернет радио имею вес..
